### ISSUE TITLE
Copy pasting a logged in link and sending it to a new user should re-direct to "homepage"

### ISSUE THREAD

**Issue by mmbotelho** [sandrina-p/papers-game#6]
# Problem
At the moment, if a user copies a url and send it to someone, that person cannot use it to use the app.
<img width="508" alt="Captura de ecrã 2020-01-06, às 19 08 45" src="https://user-images.githubusercontent.com/22004566/71837950-fbcebd80-30b7-11ea-90b9-3dc8b7c40bb9.png">

# Solution
Some sort of re-direct to the main page of the app? Let me know what you think!

**Comment by sandrina-p** [comment]
Yes, that happens if the user didn't create a profile yet. (Otherwise, they'll auto-join the group). Maybe we could ask to create the profile and then auto-join the group?

**Comment by mmbotelho** [comment]
Yes, I think that makes a lot of sense! @sandrina-p

**Comment by sandrina-p** [comment]
@mmbotelho now it says "To join you need to create a profile before!" with a button below. Please take a look. If it's okay, you can close the issue (or propose a prettier layout eheh)
