### ISSUE TITLE
Remove character limit on name creation

### ISSUE THREAD

**Issue by mmbotelho** [sandrina-p/papers-game#7]
Users might want to be called just B! Or maybe they just want to be called an emoji :D 
<img width="348" alt="Captura de ecrã 2020-01-06, às 19 13 02" src="https://user-images.githubusercontent.com/22004566/71838315-d3938e80-30b8-11ea-8fe5-484805886f77.png">

And if we're going to hide the button, let's leave it there but disabled. It's better than having nothing at all and the a button appearing out of nowhere :D

**Comment by sandrina-p** [comment]
I agree. One thing [about disabled buttons](https://axesslab.com/disabled-buttons-suck/) for you to think about it!

**Comment by mmbotelho** [comment]
OK, we can leave the button always visible and active and if there's a problem, notify the user after they click it 😄 

I can't think of any validation that makes sense for this step though. Can you think of something?

**Comment by sandrina-p** [comment]
No in terms of coding. You can have 5 "maggie" profiles. Under the wood it's created a unique profile id for each one, `maggie_[randomhash]` to avoid conflicts. However, if we have a game with 2 "maggie" the only way to distinguish them is by the avatar (if they upload one).

In summary, I think the best approach is to allow the player to rename their name if needed (something not designed/implemented yet). Idea: when joining a game, if we detect two equal players, we prompt them to be more original on their names :p

**Comment by sandrina-p** [comment]
Fixed, pushed to master.
