### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by mmbotelho** [sandrina-p/papers-game#8]
Prompt users to turn on their phones sound before starting the game. Add sound effects to:
- Guessed word;
- Next paper;
- Your turn notification sound;
- Time's up!

**Comment by mmbotelho** [comment]
A little more context on why I think that's necessary - because other players don't see the screen when it's someone's turn, having those sound cues can help other players understand what's happening. In other words, when a team member yells the correct word and the player clicks on "guessed", a "PLIM" (😂) sound goes off and teammates get that feedback, that they guessed something!

**Comment by sandrina-p** [comment]
Closing this issue to keep the focus in [the MVP project](https://github.com/sandrina-p/papers-game/projects/1)
