### ISSUE TITLE
Set logo and placeholders

### ISSUE THREAD

**Issue by mmbotelho** [sandrina-p/papers-game#9]
![IMG_4277](https://user-images.githubusercontent.com/22004566/71839604-d8a60d00-30bb-11ea-8b4f-1826e2728645.PNG)

Is it possible to change this to "Papers"? Do we have the option to change the icon as well?

**Comment by sandrina-p** [comment]
Yes, it's all possible, just not done yet 😎

**Comment by mmbotelho** [comment]
Awesome @sandrina-p 😄thank you!

**Comment by sandrina-p** [comment]
@mmbotelho I added a "placeholder" icon and did set the app name as "Papers". Puxed on master on the last commit.

Do you think we should keep this issue open while waiting for the real logo?

If you are curious, there are more things we can set/add on PWA, through its manifest. [Check this link](https://developer.mozilla.org/en-US/docs/Web/Manifest). (Keep in mind Apple might not support some of them... Chrome is more friendly on that part)
